### ISSUE TITLE
Disconnecting results in an error

### ISSUE THREAD

**Issue by ThePooN** [d-fischer/twitch-chat-client#5]
### Code

```ts
this._client = await ChatClient.forTwitchClient(twitchClient);

await this.client.connect();
await this.client.waitForRegistration();

setTimeout(() => this.client.quit(), 2000);
```

### Expected behavior

Gracefully disconnect.

### Actual Behavior

Throws a "not opened" error:
```
Error: not opened
    at WebSocket.send (./node_modules/universal-websocket-client/node_modules/ws/lib/WebSocket.js:360:18)
    at WebSocketConnection.sendRaw (./node_modules/ircv3/lib/Connection/WebSocketConnection.js:114:26)
    at WebSocketConnection.Connection.sendLine (./node_modules/ircv3/lib/Connection/Connection.js:85:18)
    at ChatClient.Client.send (./node_modules/ircv3/lib/Client.js:564:26)
    at ChatClient.Client.sendMessage (./node_modules/ircv3/lib/Client.js:591:14)
    at ./node_modules/ircv3/lib/Client.js:659:31
    at new Promise (<anonymous>)
    at ChatClient.<anonymous> (./node_modules/ircv3/lib/Client.js:653:39)
    at step (./node_modules/ircv3/lib/Client.js:56:23)
    at Object.next (./node_modules/ircv3/lib/Client.js:37:53)
    at ./node_modules/ircv3/lib/Client.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (./node_modules/ircv3/lib/Client.js:27:12)
    at ChatClient.Client.quit (./node_modules/ircv3/lib/Client.js:650:16)
```

### Environment

- Version: 2.0.0-pre.4
- Node version: v11.10.1
- Operating system: Arch Linux

**Comment by d-fischer** [comment]
Fixed in `2.0.0-pre.5`.
